version: '3'
services:
  mysql:
    image: mysql:5.5
    env_file: .env.default
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 13306:3306
    command: |
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  list-api:
    image: openjdk:8
    env_file: .env.default
    volumes:
      - ./run.sh:/home/inventory/run.sh
      - ./list-api/build/libs:/home/inventory/libs
    ports:
      - 8004:8080
    depends_on:
      - mysql
    command: bash -c "cd /home/inventory && sh run.sh"
  list-view:
    image: node:10.16.3
    volumes:
      - ./list-view:/home/inventory
    ports:
      - 8084:3000
    environment:
      - VUE_APP_API_BASE_URL=http://localhost:8004
    command: bash -c "cd /home/inventory && npm run serve"
    healthcheck:
      test: curl -sS http://localhost:8080 || exit 1
      timeout: 10s
      retries: 10
